AnnualReportGenerationSystem/AdminApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'adminApp'
urlpatterns = [
    path('/', include([
        path('adminHome', views.adminHome, name='adminHome'),
        path('ourTeam', views.ourTeam, name="ourTeam"),
        path('generateReport', views.generateReport, name="generateReport"),
        path('generateReportResult/<str:fromYear>/<str:toYear>', views.generateReportResult, name="generateReportResult"),
        path('GeneratePdf/<str:fromYear>/<str:toYear>', views.GeneratePdf, name='GeneratePdf')
    ])),

]

AnnualReportGenerationSystem/AnnualReport/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from . import views, settings

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('', views.home, name="Home"),
    path('register', views.register, name="register"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('ourTeam', views.ourTeam, name="ourTeam"),
    path('adminApp', include('AdminApp.urls')),
    path('CSE', include('CSE.urls')),
    path('IT', include('IT.urls')),
    path('Civil', include('Civil.urls')),
    path('ME', include('ME.urls')),
    path('Electrical', include('Electrical.urls')),
    path('Electronics', include('Electronics.urls')),
    path('admin/', admin.site.urls),

    
]

AnnualReportGenerationSystem/IT/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'IT'
urlpatterns = [
    path('/', include([
        path('teacherHome', views.teacherHome, name='teacherHome'),
        path('ourTeam', views.ourTeam, name="ourTeam"),
        path('teacherProfile', views.teacherProfile, name='teacherProfile'),
        path('editTeacherProfile', views.editTeacherProfile, name='editTeacherProfile'),
        path('changePassword', views.changePassword, name="changePassword"),
        path('researchPapers', views.researchPapers, name='researchPapers'),
        path('addResearchPapers', views.addResearchPapers, name="addResearchPapers"),
        path('researchPaperDelete/<str:doi>', views.researchPaperDelete, name="researchPaperDelete"),
        path('phdDetails', views.phdDetails, name="phdDetails"),
        path('showAllPhdData', views.showAllPhdData, name="showAllPhdData"),
        path('addPHD', views.addPHD, name="addPHD"),
        path('updatePhdData/<str:phd_id>', views.updatePhdData, name="updatePhdData"),
        path('phdDetailsDelete/<str:phd_id>', views.phdDetailsDelete, name="phdDetailsDelete"),
        path('studentData', views.studentData, name="studentData"),
        path('addStudentData', views.addStudentData, name="addStudentData"),
        path('importStudentData', views.importStudentData, name="importStudentData"),
        path('studentDataDelete/<str:PRN>', views.studentDataDelete, name="studentDataDelete"),
        path('bookPublished', views.bookPublished, name="bookPublished"),
        path('addBookPublished', views.addBookPublished, name="addBookPublished"),
        path('bookPublishedDelete/<str:id>', views.bookPublishedDelete, name="bookPublishedDelete"),
        path('patents', views.patents, name="patents"),
        path('addPatents', views.addPatents, name="addPatents"),
        path('patentsDelete/<str:id>', views.patentsDelete, name="patentsDelete"),
        path('facultyCompletedCourse', views.facultyCompletedCourse, name="facultyCompletedCourse"),
        path('addFacultyCompletedCourse', views.addFacultyCompletedCourse, name="addFacultyCompletedCourse"),
        path('facultyCompletedCourseDelete/<str:id>', views.facultyCompletedCourseDelete, name="facultyCompletedCourseDelete"),
        path('guidePhdDetails', views.guidePhdDetails, name="guidePhdDetails"),
        path('showAllGuidePhdData', views.showAllGuidePhdData, name="showAllGuidePhdData"),
        path('addGuidePHD', views.guideAddPHD, name="addGuidePHD"),
        path('updateGuidePhdData/<str:phd_id>', views.updateGuidePhdData, name="updateGuidePhdData"),
        path('guidePhdDetailsDelete/<str:id>', views.guidePhdDetailsDelete, name="guidePhdDetailsDelete"),
        path('googleScholarCitationDetails', views.googleScholarCitationDetails, name="googleScholarCitationDetails"),
        path('addGoogleScholarCitationDetails', views.addGoogleScholarCitationDetails, name="addGoogleScholarCitationDetails"),
        path('googleScholarCitationDetailsDelete/<str:id>', views.googleScholarCitationDetailsDelete, name="googleScholarCitationDetailsDelete"),
        path('guestLecOrganizedOrDelivered', views.guestLecOrganizedOrDelivered, name="guestLecOrganizedOrDelivered"),
        path('addguestLecOrganizedOrDelivered', views.addguestLecOrganizedOrDelivered, name="addguestLecOrganizedOrDelivered"),
        path('guestLecOrganizedOrDeliveredDelete/<str:id>', views.guestLecOrganizedOrDeliveredDelete, name="guestLecOrganizedOrDeliveredDelete"),
        path('eventConductedOrAttended', views.eventConductedOrAttended, name="eventConductedOrAttended"),
        path('addeventConductedOrAttended', views.addeventConductedOrAttended, name="addeventConductedOrAttended"),
        path('eventConductedOrAttendedDelete/<str:id>', views.eventConductedOrAttendedDelete, name="eventConductedOrAttendedDelete"),
    ])),

]

AnnualReportGenerationSystem/templates/addBookPublished.html
{% extends 'base.html' %}

{% block title %}
    Add Published Books
{% endblock %}

{% load static %}

{% block content %}
    <h1>Add Published Books</h1>
    <br>

    <form class="form-horizontal"  role="form" action="addBookPublished" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label col-lg-2" for="name_faculty">
                Faculty Name:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="name_faculty" type="text" name="name_faculty" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="title_of_book">
                Title of Book:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="title_of_book" type="text" name="title_of_book" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="name_of_publisher">
                Name of Publisher:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="name_of_publisher" type="text" name="name_of_publisher" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="date_publication">
                Publication Date:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="startDate" type="date" name="date_publication" required>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-3">
                <label class="control-label" for="ddlYears">
                    Academic Year:
                </label>
                <select name="academic_year" id="ddlYears"></select>
                -
                <select name="toYear" id="ddlYears2"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
    <br>

    <script src="{% static '/js/DateValidation.js' %}"></script>
    <script src="{% static '/js/year.js' %}"></script>
    <script src="{% static '/js/year2.js' %}"></script>
{% endblock %}

AnnualReportGenerationSystem/templates/addFacultyCompletedCourse.html
{% extends 'base.html' %}

{% block title %}
    Add Faculty Completed Course
{% endblock %}

{% load static %}

{% block content %}
    <h1>Add Faculty Completed Course</h1>
    <br>

    <form class="form-horizontal"  role="form" action="addFacultyCompletedCourse" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label col-lg-2" for="faculty_name">
                Faculty Name:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="faculty_name" type="text" name="faculty_name" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="title_course">
                Title of Course:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="title_course" type="text" name="title_course" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="startDate">
                Starting Date:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="startDate" type="date" name="starting_date" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="endDate">
                Completion Date:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="endDate" type="date" name="completion_date" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="mode">
                Mode:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="mode" type="text" name="mode" required>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-3">
                <label class="control-label" for="ddlYears">
                    Academic Year:
                </label>
                <select name="academic_year" id="ddlYears"></select>
                -
                <select name="toYear" id="ddlYears2"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
    <br>

    <script src="{% static '/js/DateValidation.js' %}"></script>
    <script src="{% static '/js/year.js' %}"></script>
    <script src="{% static '/js/year2.js' %}"></script>
{% endblock %}

AnnualReportGenerationSystem/templates/addPHD.html
{% extends 'base.html' %}

{% block title %}
    Add PHD Details
{% endblock %}

{% load static %}

{% block content %}
    <h1>Add PHD Detail</h1>
    <br>
    <!--Add a Paper-->
    <form class="form-horizontal"  role="form" action="addPHD" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label col-lg-2" for="phd_ID">
                PHD ID:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="phd_ID" type="text" name="phd_ID" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="title">
                PHD Title:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="title" type="text" name="title" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="guide_name">
                Guide Name:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="guide_name" type="text" name="guide_name" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="startDate" >
                Registration Date:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="startDate" type="date" name="registration_date" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="status">
                Status:
            </label>
            <div class="col-lg-10">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="status" id="status" value="Completed" onclick="enable()" required>
                    <label class="form-check-label" for="status">
                        Completed
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="status" id="status" value="Pursuing" onclick="disable()">
                    <label class="form-check-label" for="status">
                        Pursuing
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group" id="comp_date" hidden>
            <label class="control-label col-lg-2" for="endDate">
                Completion Date:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="endDate" type="date" name="completion_date">
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-3">
                <label class="control-label" for="ddlYears">
                    Academic Year:
                </label>
                <select name="academic_year" id="ddlYears"></select>
                -
                <select name="toYear" id="ddlYears2"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
    <br>

    {% for message in messages %}
        <script>alert("{{ message }}")</script>
    {% endfor %}

    <script>
        function disable() {
            document.getElementById("comp_date").hidden = true;
        }
        function enable() {
            document.getElementById("comp_date").hidden = false;
        }
    </script>
    <script src="{% static '/js/DateValidation.js' %}"></script>
    <script src="{% static '/js/year.js' %}"></script>
    <script src="{% static '/js/year2.js' %}"></script>
{% endblock %}

AnnualReportGenerationSystem/templates/addResearchPapers.html
{% extends 'base.html' %}

{% block title %}
    Add Research Paper
{% endblock %}

{% load static %}

{% block content %}
    <h1>Add Research Paper</h1>
    <br>
    <!--Add a Paper-->
    <form class="form-horizontal"  role="form" action="addResearchPapers" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label col-lg-2" for="doi_no">
                DOI No:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="doi_no" type="text" name="doi" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="type_of_publication">
                Type of Publication:
            </label>
            <div class="col-lg-10">
                <select class="form-select" id="type_of_publication" name="type_of_publication" required>
                    <option value="International Journal">International Journal</option>
                    <option value="International Conference">International Conference</option>
                    <option value="International Proceedings">International Proceedings</option>
                    <option value="IEEE International Conference">IEEE International Conference</option>
                    <option value="National Conference">National Conference</option>
                    <option value="National Proceeding">National Proceeding</option>
                    <option value="Book Chapter">Book Chapter</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="details_of_paper">
                Details of Paper:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="details_of_paper" type="text" name="details_of_paper" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="author_name">
                Authors Name:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="author_name" type="text" name="author_name" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="startDate">
                Publication Date:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="startDate" type="date" name="publication_date" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="department">
                Department:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="department" type="text" name="department" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="area_of_research">
                Area of Research:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="area_of_research" type="text" name="area_of_research" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-3" for="publication_details">
                Journal or Publication Details:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="publication_details" type="text" name="publication_details" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="noOfAuthor">
                No of Author:
            </label>
            <div class="col-lg-10">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="noOfAuthor" id="noOfAuthor" value="1" onclick="disable()" required>
                    <label class="form-check-label" for="noOfAuthor">
                        One
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="noOfAuthor" id="noOfAuthor" value="2" onclick="enableTwo()">
                    <label class="form-check-label" for="noOfAuthor">
                        Two
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="noOfAuthor" id="noOfAuthor" value="3" onclick="enableThree()">
                    <label class="form-check-label" for="noOfAuthor">
                        Three
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group" id="username2" hidden>
            <label class="control-label col-lg-3" for="user2">
                User Name of Author Two:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="user2" type="text" name="user2">
            </div>
        </div>
        <div class="form-group" id="username3" hidden>
            <label class="control-label col-lg-3" for="user3">
                User Name of Author Three:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="user3" type="text" name="user3">
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-3">
                <label class="control-label" for="ddlYears">
                    Academic Year:
                </label>
                <select name="academic_year" id="ddlYears"></select>
                -
                <select name="toYear" id="ddlYears2"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
    <br>

    {% for message in messages %}
        <script>alert("{{ message }}")</script>
    {% endfor %}

    <script>
        function enableTwo() {
            document.getElementById("username2").hidden = false;
            document.getElementById("username3").hidden = true;
        }
        function enableThree() {
            document.getElementById("username2").hidden = false;
            document.getElementById("username3").hidden = false;
        }
        function disable() {
            document.getElementById("username2").hidden = true;
            document.getElementById("username3").hidden = true;
        }
    </script>
    <script src="{% static '/js/DateValidation.js' %}"></script>
    <script src="{% static '/js/year.js' %}"></script>
    <script src="{% static '/js/year2.js' %}"></script>
{% endblock %}

AnnualReportGenerationSystem/templates/addeventConductedOrAttended.html
{% extends 'base.html' %}

{% block title %}
    Add Event Conducted Or Attended Details
{% endblock %}

{% load static %}

{% block content %}
    <h1>Add Event Conducted Or Attended Details</h1>
    <br>
    <form class="form-horizontal"  role="form" action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label col-lg-2" for="teacher_name">
                Teacher Name:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="teacher_name" type="text" name="teacher_name" required>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-lg-2" for="nameof_event">
                Name of Event:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="nameof_event" type="text" name="nameof_event" required>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-lg-2" for="event_details">
                Event Details:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="event_details" type="text" name="event_details" required>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-lg-2" for="startDate" >
                Starting Date:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="startDate" type="date" name="starting_date" required>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-lg-2" for="endDate" >
                Ending Date:
            </label>
            <div class="col-lg-10">
                <input class="form-control" id="endDate" type="date" name="ending_date" required>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-lg-2" for="type_of_event">
                Type of Event:
            </label>
            <div class="col-lg-10">
                <select class="form-select" id="type_of_event" name="type_of_event" required>
                    <option value="Conducted">Conducted</option>
                    <option value="Attended">Attended</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-3">
                <label class="control-label" for="ddlYears">
                    Academic Year:
                </label>
                <select name="academic_year" id="ddlYears"></select>
                -
                <select name="toYear" id="ddlYears2"></select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
    <br>

    <script src="{% static '/js/DateValidation.js' %}"></script>
    <script src="{% static '/js/year.js' %}"></script>
    <script src="{% static '/js/year2.js' %}"></script>
{% endblock %}

AnnualReportGenerationSystem/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">

    <title>
        {% block title %}
        {% endblock %}

    </title>

    <link rel="shortcut icon" href="{% static 'image/WCE_Logo.jpg' %}" type="image/x-icon">

    {#    Bootstrap CSS#}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="{% static 'css/footer_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/shadow.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <span class="navbar-brand mb-0 h1">WCE</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="mainNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">

        <ul class="navbar-nav ml-auto">

            {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link">Hello, {{user.first_name}}</a>
                </li>
                {% if isAdmin %}

                    <li class="nav-item">
                        <a class="nav-link" href="/adminApp/adminHome">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'adminApp:generateReport' %}">Generate Report</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>

                {% else %}

                    <li class="nav-item">
                        <a class="nav-link" href="teacherHome">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="teacherProfile">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% endif %}

            {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container">
    {% block content %}

    {% endblock %}
</div>

<!-- Footer -->
<footer id="footer">
    <!-- Footer Links -->
    <div class="container text-center text-md-left">
        <!-- Grid row -->
        <div class="row">
            <!-- Grid column -->
            <div class="col-lg-4 mr-auto">
                <!-- Content -->
                <h5 class="font-weight-bold text-uppercase mb-4">Address</h5>
                <p>Walchand College of Engineering,<br>
                    A/P: Vishrambagh,<br>
                    Sangli - 416 415<br>
                    Maharashtra, India<br>
                    Tel: +91-233-2300383<br>
                    Fax: +91-233-2300831<br>
                    <a href="mailto:kiran.raut@walchandsangli.ac.in">Contact Us</a>
                </p>
            </div>

            <!-- Grid column -->
            <hr class="clearfix w-100 d-md-none">
            <!-- Grid column -->
            <div class="col-lg-4 mx-auto">
                <!-- Contact details -->
                <h5 class="font-weight-bold text-uppercase mb-4">MAP</h5>
                <p>
                    <iframe
                            src="https://maps.google.com/maps?width=600&amp;height=400&amp;hl=en&amp;q=walchand college of engineering sangli&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"
                            width="100%" height="200" frameborder="0" style="border:0;" allowfullscreen=""
                            aria-hidden="false" tabindex="0"
                            aria-label="walchand college of engineering sangli"></iframe>

                </p>
            </div>
            <!-- Grid column -->
            <hr class="clearfix w-100 d-md-none">
            <!-- Grid column -->
            <div class="col-lg-4 mx-auto">
                <!-- Social buttons -->
                <h5 class="font-weight-bold text-uppercase mb-4">Our Team</h5>
                <!-- Facebook -->
                {% if isAdmin %}
                    <a href="{% url 'adminApp:ourTeam' %}" type="button" class="btn-floating btn-fb">
                        Our Team
                    </a>
                {% else %}
                    <a href="ourTeam" type="button" class="btn-floating btn-fb">
                        Our Team
                    </a>
                {% endif %}
            </div>
            <!-- Grid column -->
        </div>
        <!-- Grid row -->
    </div>
    <!-- Footer Links -->
</footer>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

AnnualReportGenerationSystem/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}WCE Home{% endblock %}

{% block content %}
    <style>
        @media screen and (min-width: 400px) {
            .clg-heading {
                margin-bottom: 0;
            }
        }
        @media screen and (min-width: 1024px) {
            .clg-heading {
                margin-bottom: 3%;
            }
        }
    </style>
    <div>
        <img style="float: left; margin-right: 5px" src="{% static '/image/Walchand_11.jpg' %}" alt="logo" />
        <h1 class="clg-heading">Walchand College of Engineering, Sangli</h1><br>
    </div>
    <div style="position: absolute">
        <h1>Annual Report Generating System</h1>
    </div>

    <br>
{% endblock %}